/* v2.6 Turn 6 — Game Feel */
(function(){
 const app=document.querySelector('#app'),C=document.querySelector('#c');if(!app||!C)return;
 const layer=document.createElement('div');layer.id='feelLayer';layer.innerHTML='<div id="roundBanner"></div><div id="battlePulse"></div><div id="unitSheet" class="hidden"><button class="closeUnit">×</button><div class="unitHero"></div><div class="unitMeta"></div></div>';app.appendChild(layer);
 const banner=layer.querySelector('#roundBanner'),sheet=layer.querySelector('#unitSheet');let oldPhase='',oldRound=-1,oldBlue=-1,oldRed=-1;
 function announce(text,kind=''){banner.className='show '+kind;banner.textContent=text;clearTimeout(announce.t);announce.t=setTimeout(()=>banner.className='',1050)}
 function pulse(kind){const p=layer.querySelector('#battlePulse');p.className=kind;setTimeout(()=>p.className='',280)}
 setInterval(()=>{let p='',r=0,b=0,red=0;try{p=phase;r=round;b=blueLives;red=redLives}catch(e){return}if(p!==oldPhase){if(p==='battle')announce('ROUND '+r,'fight');else if(oldPhase==='battle'&&p!=='battle')announce('ROUND COMPLETE','complete');oldPhase=p}if(r!==oldRound&&r>0){oldRound=r;if(p==='battle')announce('ROUND '+r,'fight')}if(oldBlue>=0&&b<oldBlue)pulse('blueHit');if(oldRed>=0&&red<oldRed)pulse('redHit');oldBlue=b;oldRed=red},180);
 C.addEventListener('pointerup',e=>{let us=[];try{us=units||[]}catch(x){return}if(!us.length)return;const rect=C.getBoundingClientRect(),x=(e.clientX-rect.left)*900/rect.width,y=(e.clientY-rect.top)*600/rect.height;let best=null,d=Infinity;for(const u of us){if(u.hp<=0)continue;const q=(u.x-x)**2+(u.y-y)**2;if(q<d){d=q;best=u}}if(!best||d>2600)return;const icons={knight:'🛡️',goose:'🪿',assassin:'🥷',sniper:'🎯',snail:'🐌',engineer:'🔧',tnt:'💣',beetank:'🐝',turtle:'🐢',goblin:'👺',merlinor:'🧙',archer:'🏹',barbarian:'🪓',spartan:'🔱',whelp:'🐲',cowboy:'🤠',spider:'🕷️',dragon:'🐉',captain:'🪝'};sheet.querySelector('.unitHero').textContent=(icons[best.type]||'⚔️')+' '+best.type.toUpperCase();sheet.querySelector('.unitMeta').innerHTML=`<b>Level ${best.l}</b><span>${Math.ceil(best.hp)} / ${Math.ceil(best.max)} HP</span><span>${best.team?'Red':'Blue'} Team</span>`;sheet.classList.remove('hidden')},{passive:true});sheet.querySelector('.closeUnit').onclick=()=>sheet.classList.add('hidden');
 document.addEventListener('click',e=>{const card=e.target.closest('.card');if(!card)return;card.classList.remove('pickPop');void card.offsetWidth;card.classList.add('pickPop')},{passive:true});
})();