/* v2.6 Turn 7 — Graphics Pass B: Showdown Lab visual identity */
(function(){
 const C=document.querySelector('#c'),app=document.querySelector('#app');if(!C||!app)return;
 const fx=document.createElement('div');fx.id='battleFX';fx.innerHTML='<div class="arenaFloor"><i></i><i></i><i></i></div><div class="arenaGlow blue"></div><div class="arenaGlow red"></div><div class="midline"></div><div class="vignette"></div>';C.parentNode.insertBefore(fx,C.nextSibling);
 const silhouettes={knight:'shield',goose:'bird',assassin:'blade',sniper:'scope',snail:'shell',engineer:'gear',turret:'turret',tnt:'bomb',beetank:'bee',mole:'mole',turtle:'shell',goblin:'goblin',merlinor:'mage',archer:'bow',barbarian:'axe',spartan:'spear',bloodvine:'vine',whelp:'drake',sixshoot:'pistol',parasite:'parasite',cowboy:'hat',agent:'agent',villain:'villain',totem:'totem',spider:'spider',dragon:'dragon',captain:'hook'};
 const glyph={shield:'◆',bird:'⌁',blade:'⌁',scope:'⊙',shell:'◒',gear:'⚙',turret:'⊥',bomb:'●',bee:'✦',mole:'⌂',goblin:'▲',mage:'✧',bow:')',axe:'⌁',spear:'↑',vine:'⌇',drake:'◇',pistol:'⌐',parasite:'✣',hat:'⌒',agent:'▰',villain:'▼',totem:'▥',spider:'✳',dragon:'◆',hook:'J'};
 let prev=new Map(),last=0;
 function burst(x,y,team,kind='hit',type=''){const b=document.createElement('i');b.className='combatBurst '+kind+' '+(team?'red':'blue')+' '+(silhouettes[type]||'');b.style.left=x+'px';b.style.top=y+'px';fx.appendChild(b);setTimeout(()=>b.remove(),520)}
 function frame(t){requestAnimationFrame(frame);if(t-last<40)return;last=t;let us=[];try{us=units||[]}catch(e){return}const r=C.getBoundingClientRect(),sx=r.width/900,sy=r.height/600;fx.style.cssText=`left:${C.offsetLeft}px;top:${C.offsetTop}px;width:${r.width}px;height:${r.height}px`;const now=new Map();for(const u of us){if(u.hp<=0)continue;now.set(u.id,{hp:u.hp,x:u.x,y:u.y,team:u.team,type:u.type});const old=prev.get(u.id);if(old&&u.hp<old&&Math.random()<.45)burst(u.x*sx,u.y*sy,u.team,'hit',u.type)}for(const[id,o]of prev)if(!now.has(id))burst(o.x*sx,o.y*sy,o.team,'ko',o.type);prev=now;let battle=false;try{battle=phase==='battle'}catch(e){}fx.classList.toggle('hidden',!battle)}requestAnimationFrame(frame);
 /* Replace emoji with a consistent emblem language while retaining archetype recognition. */
 setInterval(()=>{const unitsEls=document.querySelectorAll('#vf2 .vfunit');unitsEls.forEach(el=>{let title=el.title||'',type=title.split(' ')[0].toLowerCase();if(!type)return;const g=el.querySelector('.vfglyph');if(!g)return;const s=silhouettes[type]||'fighter';el.dataset.archetype=s;g.textContent=glyph[s]||'◆';});},220);
})();