#!/usr/bin/env python3
"""Prepare the one-fighter evolution spike; with shared body scale and per-pose foot registration."""
import importlib.util
import json
from pathlib import Path
import numpy as np
from PIL import Image
from scipy.ndimage import label, binary_dilation

ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / 'tools/art-spike/knight/evolved'
spec = importlib.util.spec_from_file_location('sheet', ROOT / 'tools/prep-authored-sheet.py')
sheet = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sheet)
rgb = np.asarray(Image.open(DEST / 'sheet-source.webp').convert('RGB'))
rgba = sheet.chroma_alpha(rgb)
labels, _ = label(rgba[:, :, 3] > 45)
areas = np.bincount(labels.ravel())
components = []
for ident in np.flatnonzero(areas > 5000):
    if ident == 0:
        continue
    ys, xs = np.where(labels == ident)
    components.append((ident, int(xs.min()), int(ys.min()), int(xs.max()+1), int(ys.max()+1)))
assert len(components) == 7, components
top = sorted([c for c in components if c[2] < rgb.shape[0] * .45], key=lambda c: c[1])
bottom = sorted([c for c in components if c[2] >= rgb.shape[0] * .45], key=lambda c: c[1])
assert len(top) == 4 and len(bottom) == 3
runtime_dir = ROOT / 'v3/assets/authored/knight/evolved'
runtime_dir.mkdir(parents=True, exist_ok=True)
registered = {'scale': 1.3, 'referenceHeight': 162.8, 'poses': {}}
feet = dict(zip(['idle','move','attack','guard','charge','hit','defeat'], [(176,506),(541,512),(900,503),(1365,506),(213,938),(802,954),(1213,936)]))
manifest = {'fighter': 'knight', 'form': 'evolved', 'levels': [5, 9],
            'status': 'branch pilot; phone visual approval pending',
            'poses': []}
for name, comp in zip(['idle', 'move', 'attack', 'guard', 'charge', 'hit', 'defeat'], top+bottom):
    ident, x0, y0, x1, y1 = comp
    assert x0 > 0 and y0 > 0 and x1 < rgb.shape[1] and y1 < rgb.shape[0], comp
    pixels = rgba.copy()
    keep = binary_dilation(labels == ident, iterations=2)
    pixels[:, :, 3][~keep] = 0
    pose = Image.fromarray(pixels)
    bounds = pose.getbbox()
    cropped = pose.crop(bounds)
    common_scale = .4
    resized = cropped.resize((round(cropped.width*common_scale), round(cropped.height*common_scale)), Image.Resampling.LANCZOS)
    prepared = Image.new('RGBA', (resized.width+12,resized.height+12))
    prepared.alpha_composite(resized,(6,6))
    prepared = sheet.add_outline(prepared)
    prepared.save(runtime_dir / (name+'.webp'), 'WEBP', lossless=True, method=6)
    fx,fy = feet[name]
    anchor = [((fx-bounds[0])*common_scale+6)/prepared.width, ((fy-bounds[1])*common_scale+6)/prepared.height]
    registered['poses']['signature' if name=='charge' else name] = {'file': name, 'width': prepared.width, 'height': prepared.height, 'anchor': anchor}

    runtime = sheet.add_outline(sheet.normalize(pose, bottom=91))
    bounds = runtime.getchannel('A').getbbox()
    assert bounds and min(bounds[:2]) > 0 and max(bounds[2:]) < 96, bounds
    runtime.save(DEST / (name + '.webp'), 'WEBP', lossless=True, method=6)
    manifest['poses'].append({'pose': name, 'source_component_bounds': [x0,y0,x1,y1],
                              'alpha_bounds': bounds, 'identity': 9, 'equipment': 9,
                              'pose_clarity': 8.5, 'critical_defects': []})
# Preserve the approved canonical bytes; registration changes only battle poses.
(runtime_dir / 'presentation.webp').write_bytes((DEST / 'presentation.webp').read_bytes())
(ROOT / 'v3/evolved-knight.js').write_text('// Generated by tools/prep-evolved-knight.py. Shared source scale; registered feet.\nwindow.KnightEvolvedArt='+json.dumps(registered,separators=(',',':'))+';\n')
(DEST / 'manifest.json').write_text(json.dumps(manifest, indent=2)+'\n')
print('Prepared seven complete candidate poses and 512px canonical; shared-scale runtime assets registered')
